sudo: required
dist: trusty
language: node_js
node_js:
  - "6.9"
  - "7.1"
install:

- npm -g install -S

- npm -v

- mkdir out

- npm install -g standard

- npm install -g babel-cli

- npm install  babel-preset-latest --save

- npm install babel --save

- npm -g install jasmine

notifications:
  webhooks:
    urls:
      - https://canary.discordapp.com/api/webhooks/258982919270301697/NP63El2OthaR58UxqrgSvCSInIQ0u3atx1AXmapuQFu1epocE9XB4ttQ2dQvI8V49m-n/travisci
      - https://canary.discordapp.com/api/webhooks/258982919270301697/NP63El2OthaR58UxqrgSvCSInIQ0u3atx1AXmapuQFu1epocE9XB4ttQ2dQvI8V49m-n/events
      - https://canary.discordapp.com/api/webhooks/258982919270301697/NP63El2OthaR58UxqrgSvCSInIQ0u3atx1AXmapuQFu1epocE9XB4ttQ2dQvI8V49m-n/notifications
      - https://canary.discordapp.com/api/webhooks/258982919270301697/NP63El2OthaR58UxqrgSvCSInIQ0u3atx1AXmapuQFu1epocE9XB4ttQ2dQvI8V49m-n/slack
    
    template: "%{repository} (%{commit}) : %{message} %{foo} - Build details: %{build_url}" #template used by the webhook to format msg
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always # default: never

script :

- babel src --no-comments --minified -D -d out









