sudo: required
dist: trusty
language: node_js
node_js:
  - "6.1"
  - "6.6"
install:
- npm -g install -S
- npm -v
- node --v8-options | grep harm
- mkdir out
- npm install -g babel-cli
script :
- babel bot.js -D -d out
