sudo: required
dist: trusty
language: node_js
node_js:
  - "6.1"
  - "6.6"
install:
- npm -g install -S
- npm -v
- node --v8-options | grep harm
- mkdir out
script :
- /node_modules/.bin/babel bot.js -d out  
