sudo: required
dist: trusty
language: node_js
node_js:
  - "6.9"
  - "7.1"
install:

- npm -g install -S

- npm -v

- mkdir out

- npm install -g standard

- npm install -g babel-cli

- npm install  babel-preset-latest --save

- npm install babel --save

- npm -g install jasmine

notifications:
  webhooks:
    urls:
      - https://canary.discordapp.com/api/webhooks/258976487443529738/WndRBOaB6Uqm-EDGbWDabtYW7jBeP2dUfIzR8Fjjitm2-AusDLYJ2wBTpRpbT8Xq60iT/travisci
      - https://canary.discordapp.com/api/webhooks/258976487443529738/WndRBOaB6Uqm-EDGbWDabtYW7jBeP2dUfIzR8Fjjitm2-AusDLYJ2wBTpRpbT8Xq60iT/events
    
    template: "%{repository} (%{commit}) : %{message} %{foo} - Build details: %{build_url}" #template used by the webhook to format msg
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always # default: never

script :

- jasmine ./test/commandLoadertests.js

- babel src --no-comments --minified -D -d out









