sudo: required
dist: trusty
addons:
  apt:
    packages:
      - nodejs-legacy
      - npm
      - node
language: node_js
node_js:
  - "6"
  - "6.1"
install:
- npm -g install
- npm -v
- babel -v
- mkdir bin
- npm build